-- Automações do atendimento: registro de cada mensagem enviada automaticamente
-- (retomada de conversa parada e cobrança). A rotina /api/lembretes usa esse registro
-- pra não mandar a mesma coisa duas vezes, e o app mostra os últimos envios na tela
-- Automações. As regras ficam em app_config (id = 'automacoes', uma linha por empresa).

create table if not exists automacao_envios (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references empresas(id),
  -- 'retomada' | 'cobranca_antes' | 'cobranca_dia' | 'cobranca_depois'
  tipo text not null,
  telefone text not null,
  nome text,
  -- retomada: horário (ms) da última mensagem do cliente; cobrança: id do lançamento
  referencia text,
  mensagem text,
  enviado_em timestamptz not null default now()
);
create index if not exists automacao_envios_busca on automacao_envios (empresa_id, tipo, telefone, enviado_em desc);

-- só quem grava é a rotina do servidor (chave de serviço, com empresa_id explícito);
-- o app só lê — por isso sem trigger de empresa_id, e com as mesmas políticas de
-- leitura da tabela "conversas" (quem atende enxerga os envios da própria empresa)
alter table automacao_envios enable row level security;
do $$
declare
  pol record;
  novo_nome text;
begin
  for pol in
    select policyname, permissive, roles, cmd, qual, with_check
    from pg_policies
    where schemaname = 'public' and tablename = 'conversas'
  loop
    novo_nome := pol.policyname || ' (automacao_envios)';
    execute format('drop policy if exists %I on automacao_envios', novo_nome);
    execute format(
      'create policy %I on automacao_envios as %s for %s to %s%s%s',
      novo_nome,
      case when pol.permissive = 'PERMISSIVE' then 'permissive' else 'restrictive' end,
      pol.cmd,
      array_to_string(pol.roles, ', '),
      case when pol.qual is not null then format(' using (%s)', pol.qual) else '' end,
      case when pol.with_check is not null then format(' with check (%s)', pol.with_check) else '' end
    );
  end loop;
end $$;

select tablename, count(*) as politicas
from pg_policies
where schemaname = 'public' and tablename in ('conversas', 'automacao_envios')
group by tablename;
