-- Métricas do atendimento e pesquisa de satisfação.
-- telefone sempre só com dígitos (ex: 5511987654321), igual nos dois lados (app e webhook).

-- linha do tempo de cada conversa — de onde saem "tempo até a 1ª resposta",
-- "tempo até resolver" e "% resolvidas só pela IA" no Painel de Atendimento.
--   cliente_msg     → webhook, a cada mensagem recebida do cliente
--   resposta_ia     → webhook, quando a IA responde
--   resposta_humano → app, quando um atendente envia mensagem pelo app (autor = usuário)
--   assumida        → app, quando um atendente assume a conversa
--   resolvida       → app, quando a conversa é marcada como resolvida
create table if not exists atendimento_eventos (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references empresas(id),
  telefone text not null,
  tipo text not null,
  autor text,
  em timestamptz not null default now()
);
create index if not exists atendimento_eventos_busca on atendimento_eventos (empresa_id, em desc);

-- pesquisa enviada ao resolver a conversa; o webhook grava a nota quando o cliente responde
create table if not exists pesquisas_satisfacao (
  id bigint primary key,
  empresa_id uuid not null references empresas(id),
  telefone text not null,
  nome text,
  atendente text,
  -- pendente → respondida (nota 1..5) | sem_nota (respondeu outra coisa) | expirada (24h sem resposta)
  status text not null default 'pendente',
  nota int check (nota between 1 and 5),
  comentario text,
  agradecimento text,
  enviada_em timestamptz not null default now(),
  respondida_em timestamptz
);
create index if not exists pesquisas_satisfacao_tel on pesquisas_satisfacao (empresa_id, telefone, enviada_em desc);

-- empresa_id automático (o webhook manda explícito; o app deixa o gatilho preencher)
-- e as mesmas políticas de RLS da tabela "conversas" (quem atende lê e grava)
do $$
declare
  t text;
  pol record;
  novo_nome text;
begin
  foreach t in array array['atendimento_eventos', 'pesquisas_satisfacao'] loop
    execute format('drop trigger if exists trg_set_empresa_id on %I', t);
    execute format('create trigger trg_set_empresa_id before insert on %I for each row execute function set_empresa_id()', t);
    execute format('alter table %I enable row level security', t);
    for pol in
      select policyname, permissive, roles, cmd, qual, with_check
      from pg_policies
      where schemaname = 'public' and tablename = 'conversas'
    loop
      novo_nome := pol.policyname || ' (' || t || ')';
      execute format('drop policy if exists %I on %I', novo_nome, t);
      execute format(
        'create policy %I on %I as %s for %s to %s%s%s',
        novo_nome, t,
        case when pol.permissive = 'PERMISSIVE' then 'permissive' else 'restrictive' end,
        pol.cmd,
        array_to_string(pol.roles, ', '),
        case when pol.qual is not null then format(' using (%s)', pol.qual) else '' end,
        case when pol.with_check is not null then format(' with check (%s)', pol.with_check) else '' end
      );
    end loop;
  end loop;
end $$;

select tablename, count(*) as politicas
from pg_policies
where schemaname = 'public' and tablename in ('conversas', 'atendimento_eventos', 'pesquisas_satisfacao')
group by tablename;
