-- Instagram (Direct + comentários) via API oficial da Meta — um app da DeOli, e cada
-- empresa conecta a própria conta pelo botão "Conectar Instagram" (login do Instagram).

-- conta do Instagram conectada por empresa. O token NUNCA vai para o navegador: a tabela
-- tem RLS ligado e nenhuma política, então só o servidor (chave de serviço) lê/grava.
create table if not exists instagram_contas (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references empresas(id),
  ig_user_id text not null unique,       -- id da conta profissional (vem em entry.id nos webhooks)
  app_user_id text,                      -- id devolvido no login (usado nos pedidos de exclusão da Meta)
  username text,
  nome text,
  access_token text not null,            -- token de longa duração (60 dias, renovado pela rotina)
  token_expira_em timestamptz,
  conectado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  ativo boolean not null default true
);
create index if not exists instagram_contas_empresa on instagram_contas (empresa_id);
alter table instagram_contas add column if not exists app_user_id text;
alter table instagram_contas enable row level security;

-- mensagens do Direct (recebidas e enviadas) — o app lê para montar a conversa; quem grava
-- é o servidor (webhook da Meta e envio pelo app passando pelo servidor)
create table if not exists ig_mensagens (
  id bigint generated by default as identity primary key,
  empresa_id uuid not null references empresas(id),
  ig_user_id text not null,              -- conta da empresa
  igsid text not null,                   -- id do contato no Instagram (Instagram-scoped id)
  from_me boolean not null default false,
  texto text,
  midia_url text,
  mid text,                              -- id da mensagem na Meta (evita processar 2x)
  em timestamptz not null default now()
);
create unique index if not exists ig_mensagens_mid on ig_mensagens (mid) where mid is not null;
create index if not exists ig_mensagens_conversa on ig_mensagens (empresa_id, igsid, em);

-- leitura pelo app com as mesmas políticas de "conversas" (quem atende vê as mensagens da
-- própria empresa); o gatilho de empresa_id respeita o valor explícito mandado pelo servidor
do $$
declare
  pol record;
  novo_nome text;
begin
  execute 'drop trigger if exists trg_set_empresa_id on ig_mensagens';
  execute 'create trigger trg_set_empresa_id before insert on ig_mensagens for each row execute function set_empresa_id()';
  execute 'alter table ig_mensagens enable row level security';
  for pol in
    select policyname, permissive, roles, cmd, qual, with_check
    from pg_policies
    where schemaname = 'public' and tablename = 'conversas'
  loop
    novo_nome := pol.policyname || ' (ig_mensagens)';
    execute format('drop policy if exists %I on ig_mensagens', novo_nome);
    execute format(
      'create policy %I on ig_mensagens as %s for %s to %s%s%s',
      novo_nome,
      case when pol.permissive = 'PERMISSIVE' then 'permissive' else 'restrictive' end,
      pol.cmd,
      array_to_string(pol.roles, ', '),
      case when pol.qual is not null then format(' using (%s)', pol.qual) else '' end,
      case when pol.with_check is not null then format(' with check (%s)', pol.with_check) else '' end
    );
  end loop;
end $$;

select tablename, count(*) as politicas
from pg_policies
where schemaname = 'public' and tablename in ('conversas', 'ig_mensagens', 'instagram_contas')
group by tablename;
